# Job Template(s)
.tcltm: &tcltm
  stage: build
  tags:
    - docker
  image: datacore/tcltm:latest
  script:
    - tcltm
  artifacts:
    paths:
      - shell-*.tm

stages:
  - build

build::master:
  <<: *tcltm
  except:
    - tags
  artifacts:
    paths:
      - shell-*.tm
    expire_in: 15m
    
build::release:
  <<: *tcltm
  only:
    - tags
